#!/bin/sh
echo "$1"

if ["$1" == "production"];
then
	echo "Production Env"
        yml="production.yml"
else
	echo "Local Env"
        yml="local.yml"
fi

echo "Build in $yml enviroment"
docker-compose -f $yml build

